---
- name: Deploy FastAPI container
  hosts: fastapi_servers
  become: true
  tasks:
    - name: Install Docker
      yum:
        name: docker
        state: present

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes
    
    - name: Copy FastAPI app to EC2
      copy:
        src: .
        dest: /home/ubuntu/fastapi-devops-demo/


    - name: Build FastAPI Docker image
      community.docker.docker_image:
        name: fastapi-app
        source: build
        build:
          path: /home/ubuntu/fastapi-devops-demo
         

    - name: Run FastAPI container
      community.docker.docker_container:
        name: fastapi
        image: fastapi-app
        ports:
          - "80:8000"
        restart_policy: always